### ISSUE TITLE
Copy graph topology (image) to clipboard

### ISSUE THREAD

**Issue by GoogleCodeExporter** [cplussharp/graph-studio-next#261]
```
We, of course, have Save as PNG option already, and Alt+PrintScreen gets the 
visual window image into clipboard, however it would be nice to also have a 
menu option to put what we save into file into clipboard, e.g. for pasting into 
email.
```

Original issue reported on code.google.com by `rylt...@gmail.com` on 19 Dec 2014 at 2:34

**Comment by roman380** [comment]
I found that this image is already put to clipboard without need when saving. I don't think it's good and I added bool parameter to possibly change it, but let it be as is for a while

**Comment by mikecopperwhite** [comment]
I agree, GSN should not be automatically copying to clipboard during file saving. Copying to clipboard is only supposed to happen when requested by the user. Have no problem if you'd like to change it.
