### ISSUE TITLE
New feature : Save text/graph information and tweaks to text information

### ISSUE THREAD

**Issue by mikecopperwhite** [cplussharp/graph-studio-next#277]
New menu item File/Save Graph information - should save to a text file the same information as shown in the Text Information window on highest detail level (same information as Copy Text Information Window to Clipboard). Should this be a Unicode text file? It would be easier in some ways if it was an ASCII file.

There should be a new file option - "Always save Graph Information" so that this information can be always saved to a .txt extension on every save alongside GRF/GRFX/PNG.

Perhaps rename "Text Information" in menu item and window title to "Graph Information" for consistency (Graph statistics, Graph Events, Graph Information) and clarity. 

Give the text/graph information a proper title bar with minimize and maximize buttons for ease of use.

Perhaps text information window could default to maximum detail level with easy keyboard shortcuts for changing information detail level.

**Comment by roman380** [comment]
I myself never used text information at level different than highest. Then I used that window to copy the text, and it's opening the window, choosing level, refresh, then copy to clipboard, close windows - too many steps. Doing this over slow remote connection is not fun. 

Now we have Ctrl+Alt+C to get this done faster without showing the helper window.

If saving to file, the same GetReportText function can be used. I would suggest that this Unicode string is converted to UTF-8 and saved into text file, with or without UTF-8 [BOM header/prefix](https://en.wikipedia.org/wiki/Byte_order_mark). This is almost the same as ASCII with the difference for non-[Latin](https://en.wikipedia.org/wiki/List_of_Unicode_characters#Basic_Latin) characters (and they are rare in those files).
