### ISSUE TITLE
Appveyor build binaries have different version number from Appveyor version number

### ISSUE THREAD

**Issue by mikecopperwhite** [cplussharp/graph-studio-next#299]
For example Appveyor page https://ci.appveyor.com/project/cplussharp/graph-studio-next/build/0.7.1.6
gives version number as 0.7.1.6 but version number on graphstudionext.exe is 0.7.1.0

Not familiar with Appveyor and whether it's possible for Appveyor to change the resource version number. Perhaps it's just a FAQ if not.

**Comment by cplussharp** [comment]
I think the version number is an Environment Variable during the Appveyor build. I didn't had time to figure out how to include this during build.

**Comment by mikecopperwhite** [comment]
Looks like we have a choice between the full version with dot separators e.g 0.7.1.9 or just the build number e.g. 9

Not sure how to convert dot separated Appveyor version 0.7.1.9 into the comma separated version that will work with the version info resource. 

The alternative is to hardcode the first three digits of the version number in VersionNo.h and use the Appveyor build number for the last digit if it's available.

**Comment by cplussharp** [comment]
Seems we have worked on the same issue ;)
I have removed the appveyor text and included some conditional comments for the PreprocessorDefinitions in the project files. Because if the envvar APPVEYOR_BUILD_VERSION is not set the definition is empty and I couldn't build localy.

**Comment by mikecopperwhite** [comment]
Seems fixed now. Not much point in auto generating build number for local builds.

**Comment by cplussharp** [comment]
Seems fixed
