### ISSUE TITLE
DXVA Null Renderer: Class not registered

### ISSUE THREAD

**Issue by mirh** [cplussharp/graph-studio-next#310]
```
REGDB_E_CLASSNOTREG (0x80040154)
Can't create renderer (decimal -214722164)
```

This happens in Performance Test with it seems every decoder. I'm on W7.

**Comment by mikecopperwhite** [comment]
Thanks for the report. That last rev should fix that problem, it was a relatively simple oversight in the code. Also will allow this filter to be loaded from GRF and GRFX files (in GSN ony, not other graph editors as it's an internal GSN filter).
