### ISSUE TITLE
Blacklisting VMR7 stops all video rendering

### ISSUE THREAD

**Issue by mentaur** [cplussharp/graph-studio-next#334]
The VMR7 doesn't work for me, but EVR and VMR9 do, so want to find a way to prevent the VMR7 from coming up, or being able to select a different default video renderer.

When I blacklist the Video Renderer filter (I get two in my list so I do both) now I can no longer render any video streams

**Comment by clsid2** [comment]
That is because both EVR and VMR9 have a merit equal to MERIT_DO_NOT_USE. Increase the merit of the one that you want to use. Probably best to keep it low, like MERIT_DO_NOT_USE + 1.
