### ISSUE TITLE
Buttons at top of Favorite Filters too small on 4k display at 175%

### ISSUE THREAD

**Issue by ReggThims** [cplussharp/graph-studio-next#335]
As ever, many thanks for this great/useful/more superlatives... tool.
There are 3 buttons with text far too small to read at the top of the Favorite Filters page. I'm sure these are just fine on a standard monitor... It may be that the font used is OK and the problem is just that the button height has not been scaled.

![image](https://user-images.githubusercontent.com/6677063/72077090-931d5600-32ee-11ea-9469-649ca6109b62.png)

**Comment by ReggThims** [comment]
I should have thought of that... thanks.

**Comment by roman380** [comment]
The question overall makes sense and the app could have taken care of scaling. But... someone needs to put effort into all this, and before this is done the scaling override is of great help.

**Comment by ReggThims** [comment]
Yes; I have spent hours working over a large MFC application to make it look pretty on 4K with multiple screens all set to different scales. It's a lot of (tedious) work.
