### ISSUE TITLE
graph-studio (32bit) crashes on opening application

### ISSUE THREAD

**Issue by Petje1972** [cplussharp/graph-studio-next#337]
Hi,
For some time now I have the issue that opening graphstudio (32bit version) will close after 1 second or so.
I have downloaded the source code and running in debug mode I notice that the application is crashing because of an exception in `int FilterTemplates::AddFilters(IEnumMoniker *emoniker, int enumtype, GUID category)` when opening 'quartz.dll'.

Does anybody know how to resolve the issue?

Best regards
Patrick Vossen

**Comment by mikecopperwhite** [comment]
Hard to know whether this is a problem with GraphStudioNext or a system specific problem with the registered filters on your system which AddFilters is enumerating or a configuration problem with quartz.dll (Windows 10 has had some regressions of DirectShow functionality recently) without more information.

Can you capture a minidump file or at least a stack trace of the crash. You can do this in visual studio by opening the exe as a project and running with Debug/Go.

**Comment by Petje1972** [comment]
Hi,
I have opened the GraphStudioNext.exe using VS2019.
On exception (Exception thrown at 0x05AF40F0 in GraphStudioNext.exe: 0xC0000005: Access violation executing location 0x05AF40F0.) I am not able to copy the details (OpenClipboardFailed error from VS)
But I have created a dump file. Please download using following link : [downloadlink](http://my.bcmdisplaysystems.com/graphstudionext.dmp)

Grtz P

**Comment by roman380** [comment]
If you are opening this from Visual Studio IDE debugger, can you post debug output log from three? Specifically, list of last loaded DLLs before the thing crashes.

**Comment by Petje1972** [comment]
I've got no debug output...

**Comment by Petje1972** [comment]
Sorry, I've extended my logging;
--------
'graphstudionext.exe' (Win32): Loaded 'C:\Users\Patrick Vossen\Downloads\graph-studio-next-master (1)\graph-studio-next-master\bin\graphstudionext.exe'. Symbols loaded.
'graphstudionext.exe' (Win32): Loaded 'C:\Windows\SysWOW64\ntdll.dll'. 
'graphstudionext.exe' (Win32): Loaded 'C:\Windows\SysWOW64\kernel32.dll'. 
'graphstudionext.exe' (Win32): Loaded 'C:\Windows\SysWOW64\KernelBase.dll'. 
'graphstudionext.exe' (Win32): Loaded 'C:\Windows\SysWOW64\user32.dll'. 
'graphstudionext.exe' (Win32): Loaded 'C:\Windows\SysWOW64\win32u.dll'. 
'graphstudionext.exe' (Win32): Loaded 'C:\Windows\SysWOW64\quartz.dll'. 
'graphstudionext.exe' (Win32): Loaded 'C:\Windows\SysWOW64\msdmo.dll'. 
'graphstudionext.exe' (Win32): Loaded 'C:\Windows\SysWOW64\gdi32.dll'. 
'graphstudionext.exe' (Win32): Loaded 'C:\Windows\SysWOW64\msvcrt.dll'. 
'graphstudionext.exe' (Win32): Loaded 'C:\Windows\SysWOW64\msvcrt.dll'. 
'graphstudionext.exe' (Win32): Unloaded 'C:\Windows\SysWOW64\msvcrt.dll'
'graphstudionext.exe' (Win32): Loaded 'C:\Windows\SysWOW64\combase.dll'. 
'graphstudionext.exe' (Win32): Loaded 'C:\Windows\SysWOW64\gdi32full.dll'. 
'graphstudionext.exe' (Win32): Loaded 'C:\Windows\SysWOW64\advapi32.dll'. 
'graphstudionext.exe' (Win32): Loaded 'C:\Windows\SysWOW64\ucrtbase.dll'. 
'graphstudionext.exe' (Win32): Loaded 'C:\Windows\SysWOW64\msvcp_win.dll'. 
'graphstudionext.exe' (Win32): Loaded 'C:\Windows\SysWOW64\sechost.dll'. 
'graphstudionext.exe' (Win32): Loaded 'C:\Windows\SysWOW64\rpcrt4.dll'. 
'graphstudionext.exe' (Win32): Loaded 'C:\Windows\SysWOW64\rpcrt4.dll'. 
'graphstudionext.exe' (Win32): Loaded 'C:\Windows\SysWOW64\shell32.dll'. 
'graphstudionext.exe' (Win32): Unloaded 'C:\Windows\SysWOW64\rpcrt4.dll'
'graphstudionext.exe' (Win32): Loaded 'C:\Windows\SysWOW64\sspicli.dll'. 
'graphstudionext.exe' (Win32): Loaded 'C:\Windows\SysWOW64\cfgmgr32.dll'. 
'graphstudionext.exe' (Win32): Loaded 'C:\Windows\SysWOW64\cryptbase.dll'. 
'graphstudionext.exe' (Win32): Loaded 'C:\Windows\SysWOW64\ole32.dll'. 
'graphstudionext.exe' (Win32): Loaded 'C:\Windows\SysWOW64\msimg32.dll'. 
'graphstudionext.exe' (Win32): Loaded 'C:\Windows\SysWOW64\SHCore.dll'. 
'graphstudionext.exe' (Win32): Loaded 'C:\Windows\SysWOW64\bcryptprimitives.dll'. 
'graphstudionext.exe' (Win32): Loaded 'C:\Windows\SysWOW64\oleaut32.dll'. 
'graphstudionext.exe' (Win32): Loaded 'C:\Windows\SysWOW64\windows.storage.dll'. 
'graphstudionext.exe' (Win32): Loaded 'C:\Windows\SysWOW64\windows.storage.dll'. 
'graphstudionext.exe' (Win32): Unloaded 'C:\Windows\SysWOW64\windows.storage.dll'
'graphstudionext.exe' (Win32): Loaded 'C:\Windows\SysWOW64\winspool.drv'. 
'graphstudionext.exe' (Win32): Loaded 'C:\Windows\SysWOW64\profapi.dll'. 
'graphstudionext.exe' (Win32): Loaded 'C:\Windows\SysWOW64\shlwapi.dll'. 
'graphstudionext.exe' (Win32): Loaded 'C:\Windows\SysWOW64\kernel.appcore.dll'. 
'graphstudionext.exe' (Win32): Loaded 'C:\Windows\SysWOW64\powrprof.dll'. 
'graphstudionext.exe' (Win32): Loaded 'C:\Windows\SysWOW64\bcrypt.dll'. 
'graphstudionext.exe' (Win32): Loaded 'C:\Windows\SysWOW64\umpdc.dll'. 
'graphstudionext.exe' (Win32): Loaded 'C:\Windows\SysWOW64\cryptsp.dll'. 
'graphstudionext.exe' (Win32): Loaded 'C:\Windows\SysWOW64\winmm.dll'. 
'graphstudionext.exe' (Win32): Loaded 'C:\Windows\SysWOW64\IPHLPAPI.DLL'. 
'graphstudionext.exe' (Win32): Loaded 'C:\Windows\SysWOW64\propsys.dll'. 
'graphstudionext.exe' (Win32): Loaded 'C:\Windows\SysWOW64\psapi.dll'. 
'graphstudionext.exe' (Win32): Loaded 'C:\Windows\SysWOW64\ws2_32.dll'. 
'graphstudionext.exe' (Win32): Loaded 'C:\Windows\SysWOW64\imm32.dll'. 
'graphstudionext.exe' (Win32): Loaded 'C:\Windows\SysWOW64\winmmbase.dll'. 
'graphstudionext.exe' (Win32): Loaded 'C:\Windows\SysWOW64\winmmbase.dll'. 
'graphstudionext.exe' (Win32): Loaded 'C:\Windows\SysWOW64\winmmbase.dll'. 
'graphstudionext.exe' (Win32): Unloaded 'C:\Windows\SysWOW64\winmmbase.dll'
'graphstudionext.exe' (Win32): Unloaded 'C:\Windows\SysWOW64\winmmbase.dll'
'graphstudionext.exe' (Win32): Loaded 'C:\Windows\WinSxS\x86_microsoft.windows.common-controls_6595b64144ccf1df_6.0.18362.836_none_2e71f01a278b41f3\comctl32.dll'. 
'graphstudionext.exe' (Win32): Loaded 'C:\Windows\SysWOW64\uxtheme.dll'. 
'graphstudionext.exe' (Win32): Loaded 'C:\Windows\WinSxS\x86_microsoft.windows.gdiplus_6595b64144ccf1df_1.1.18362.836_none_5f5ce2ff821dbbc1\GdiPlus.dll'. 
'graphstudionext.exe' (Win32): Loaded 'C:\Windows\SysWOW64\oledlg.dll'. 
'graphstudionext.exe' (Win32): Loaded 'C:\Windows\SysWOW64\oleacc.dll'. 
'graphstudionext.exe' (Win32): Loaded 'C:\Windows\SysWOW64\version.dll'. 
'graphstudionext.exe' (Win32): Loaded 'C:\Windows\SysWOW64\xmllite.dll'. 
'graphstudionext.exe' (Win32): Loaded 'C:\Windows\SysWOW64\msctf.dll'. 
'graphstudionext.exe' (Win32): Loaded 'C:\Windows\SysWOW64\clbcatq.dll'. 
'graphstudionext.exe' (Win32): Loaded 'C:\Windows\SysWOW64\qcap.dll'. 
'graphstudionext.exe' (Win32): Loaded 'C:\Windows\SysWOW64\msvfw32.dll'. 
'graphstudionext.exe' (Win32): Loaded 'C:\Windows\SysWOW64\TextInputFramework.dll'. 
'graphstudionext.exe' (Win32): Loaded 'C:\Windows\SysWOW64\CoreMessaging.dll'. 
'graphstudionext.exe' (Win32): Loaded 'C:\Windows\SysWOW64\CoreUIComponents.dll'. 
'graphstudionext.exe' (Win32): Loaded 'C:\Windows\SysWOW64\ntmarta.dll'. 
'graphstudionext.exe' (Win32): Loaded 'C:\Windows\SysWOW64\WinTypes.dll'. 
'graphstudionext.exe' (Win32): Loaded 'C:\Windows\SysWOW64\WinTypes.dll'. 
'graphstudionext.exe' (Win32): Unloaded 'C:\Windows\SysWOW64\WinTypes.dll'
'graphstudionext.exe' (Win32): Loaded 'C:\Windows\SysWOW64\iertutil.dll'. 
'graphstudionext.exe' (Win32): Loaded 'C:\Windows\SysWOW64\coml2.dll'. 
'graphstudionext.exe' (Win32): Loaded 'C:\Windows\SysWOW64\apphelp.dll'. 
'graphstudionext.exe' (Win32): Loaded 'C:\Windows\SysWOW64\dlnashext.dll'. 
'graphstudionext.exe' (Win32): Loaded 'C:\Windows\SysWOW64\wpdshext.dll'. 
'graphstudionext.exe' (Win32): Loaded 'C:\Windows\SysWOW64\policymanager.dll'. 
'graphstudionext.exe' (Win32): Loaded 'C:\Windows\SysWOW64\msvcp110_win.dll'. 
'graphstudionext.exe' (Win32): Loaded 'C:\Windows\SysWOW64\ExplorerFrame.dll'. 
'graphstudionext.exe' (Win32): Loaded 'C:\Windows\SysWOW64\devenum.dll'. 
'graphstudionext.exe' (Win32): Loaded 'C:\Windows\SysWOW64\setupapi.dll'. 
'graphstudionext.exe' (Win32): Loaded 'C:\Windows\SysWOW64\devobj.dll'. 
'graphstudionext.exe' (Win32): Loaded 'C:\Windows\SysWOW64\wintrust.dll'. 
'graphstudionext.exe' (Win32): Loaded 'C:\Windows\SysWOW64\msasn1.dll'. 
'graphstudionext.exe' (Win32): Loaded 'C:\Windows\SysWOW64\crypt32.dll'. 
'graphstudionext.exe' (Win32): Loaded 'C:\Windows\SysWOW64\MMDevAPI.dll'. 
'graphstudionext.exe' (Win32): Loaded 'C:\Windows\SysWOW64\wdmaud.drv'. 
'graphstudionext.exe' (Win32): Loaded 'C:\Windows\SysWOW64\ksuser.dll'. 
'graphstudionext.exe' (Win32): Loaded 'C:\Windows\SysWOW64\avrt.dll'. 
'graphstudionext.exe' (Win32): Loaded 'C:\Windows\SysWOW64\AudioSes.dll'. 
'graphstudionext.exe' (Win32): Loaded 'C:\Windows\SysWOW64\msacm32.drv'. 
'graphstudionext.exe' (Win32): Loaded 'C:\Windows\SysWOW64\msacm32.dll'. 
'graphstudionext.exe' (Win32): Loaded 'C:\Windows\SysWOW64\midimap.dll'. 
'graphstudionext.exe' (Win32): Loaded 'C:\Windows\SysWOW64\avicap32.dll'. 
'graphstudionext.exe' (Win32): Unloaded 'C:\Windows\SysWOW64\avicap32.dll'
'graphstudionext.exe' (Win32): Loaded 'C:\Windows\SysWOW64\dsound.dll'. 
'graphstudionext.exe' (Win32): Loaded 'C:\Windows\SysWOW64\iccvid.dll'. 
'graphstudionext.exe' (Win32): Unloaded 'C:\Windows\SysWOW64\iccvid.dll'
'graphstudionext.exe' (Win32): Loaded 'C:\Windows\SysWOW64\iyuv_32.dll'. 
'graphstudionext.exe' (Win32): Unloaded 'C:\Windows\SysWOW64\iyuv_32.dll'
'graphstudionext.exe' (Win32): Loaded 'C:\Windows\SysWOW64\iyuv_32.dll'. 
'graphstudionext.exe' (Win32): Unloaded 'C:\Windows\SysWOW64\iyuv_32.dll'
'graphstudionext.exe' (Win32): Loaded 'C:\Windows\SysWOW64\msrle32.dll'. 
'graphstudionext.exe' (Win32): Unloaded 'C:\Windows\SysWOW64\msrle32.dll'
'graphstudionext.exe' (Win32): Loaded 'C:\Windows\SysWOW64\msvidc32.dll'. 
'graphstudionext.exe' (Win32): Unloaded 'C:\Windows\SysWOW64\msvidc32.dll'
'graphstudionext.exe' (Win32): Loaded 'C:\Windows\SysWOW64\msyuv.dll'. 
'graphstudionext.exe' (Win32): Unloaded 'C:\Windows\SysWOW64\msyuv.dll'
'graphstudionext.exe' (Win32): Loaded 'C:\Windows\SysWOW64\msyuv.dll'. 
'graphstudionext.exe' (Win32): Unloaded 'C:\Windows\SysWOW64\msyuv.dll'
'graphstudionext.exe' (Win32): Loaded 'C:\Windows\SysWOW64\tsbyuv.dll'. 
'graphstudionext.exe' (Win32): Unloaded 'C:\Windows\SysWOW64\tsbyuv.dll'
'graphstudionext.exe' (Win32): Loaded 'C:\Windows\SysWOW64\msyuv.dll'. 
'graphstudionext.exe' (Win32): Unloaded 'C:\Windows\SysWOW64\msyuv.dll'
'graphstudionext.exe' (Win32): Loaded 'C:\Windows\SysWOW64\pvwv220.dll'. Module was built without symbols.
'graphstudionext.exe' (Win32): Unloaded 'C:\Windows\SysWOW64\pvwv220.dll'
'graphstudionext.exe' (Win32): Loaded 'C:\Windows\SysWOW64\pvmjpg21.dll'. Module was built without symbols.
Unhandled exception at 0x0679D0F0 in graphstudionext.exe: 0xC0000005: Access violation executing location 0x0679D0F0.

**Comment by mikecopperwhite** [comment]
This looks like a crash in the PIC Video mjpeg codec (pvmjpg21.dll) while all the registered filters are being enumerated.

As it's low down in its address range it could be crashing when the DLL is first being loaded (DllMain). Roman's suggestion of listing the most recently loaded DLLs before the crash from the debug output window is a good one (view output window/debug from the drop down).

Try uninstalling the PIC video mjpeg code and launching GraphStudioNext again. Try reinstalling PIC video if needed. Check that the licence or trial licence is valid. The PIC video codecs may also have anti-debugging protection built in (I'm not familiar with this product).

Stack trace below:

 	05af40f0()	Unknown	Non-user code
 	[Frames below may be incorrect and/or missing]	Unknown	No symbols loaded.
>	pvmjpg21.dll!1000e53a()	Unknown	Non-user code. Binary was not built with debug information.
 	pvmjpg21.dll!1000e594()	Unknown	Non-user code. Binary was not built with debug information.
 	pvmjpg21.dll!1000d58e()	Unknown	Non-user code. Binary was not built with debug information.
 	pvmjpg21.dll!10009e14()	Unknown	Non-user code. Binary was not built with debug information.
 	pvmjpg21.dll!10002687()	Unknown	Non-user code. Binary was not built with debug information.
 	pvmjpg21.dll!1000c68a()	Unknown	Non-user code. Binary was not built with debug information.
 	pvmjpg21.dll!1000b226()	Unknown	Non-user code. Binary was not built with debug information.
 	pvmjpg21.dll!10005e71()	Unknown	Non-user code. Binary was not built with debug information.
 	msvfw32.dll!_ICSendMessage@16()	Unknown	Non-user code. Symbols loaded.
 	msvfw32.dll!_ICOpen@12()	Unknown	Non-user code. Symbols loaded.
 	devenum.dll!CIcmCoClassManager::CreateRegKeys(struct IFilterMapper2 *)	Unknown	Non-user code. Symbols loaded.
 	devenum.dll!CClassManagerBase::VerifyRegistryInSync(struct IEnumMoniker *)	Unknown	Non-user code. Symbols loaded.
 	devenum.dll!CClassManagerBase::CreateClassEnumerator(struct _GUID const &,struct IEnumMoniker * *,unsigned long)	Unknown	Non-user code. Symbols loaded.
 	devenum.dll!CCreateSwEnum::CreateClassEnumerator(struct _GUID const &,struct IEnumMoniker * *,unsigned long,struct IEnumMoniker * *)	Unknown	Non-user code. Symbols loaded.
 	devenum.dll!CCreateSwEnum::CreateClassEnumerator(struct _GUID const &,struct IEnumMoniker * *,unsigned long)	Unknown	Non-user code. Symbols loaded.
 	quartz.dll!CMapperCache::Cache()	Unknown	Non-user code. Symbols loaded.
 	quartz.dll!CMapperCache::Refresh()	Unknown	Non-user code. Symbols loaded.
 	quartz.dll!CMapperCache::RegEnumFilterInfo()	Unknown	Non-user code. Symbols loaded.
 	quartz.dll!CEnumRegMonikers::Next()	Unknown	Non-user code. Symbols loaded.
 	GraphStudioNext.exe!005654f6()	Unknown	Non-user code. Binary was not built with debug information.
 	quartz.dll!CAggDirectDraw::AddRef(void)	Unknown	Non-user code. Symbols loaded.
 	quartz.dll!_GetInterface@8()	Unknown	Non-user code. Symbols loaded.
 	quartz.dll!CEnumRegMonikers::NonDelegatingQueryInterface(struct _GUID const &,void * *)	Unknown	Non-user code. Symbols loaded.
 	quartz.dll!CFilterMapper2::EnumMatchingFilters()	Unknown	Non-user code. Symbols loaded.
 	GraphStudioNext.exe!0056b1bf()	Unknown	Non-user code. Binary was not built with debug information.
 	GraphStudioNext.exe!0051d548()	Unknown	Non-user code. Binary was not built with debug information.
 	GraphStudioNext.exe!002fa7cc()	Unknown	Non-user code. Binary was not built with debug information.
 	GraphStudioNext.exe!002f93d0()	Unknown	Non-user code. Binary was not built with debug information.
 	user32.dll!__InternalCallWinProc@20()	Unknown	Non-user code. Symbols loaded.
 	GraphStudioNext.exe!002fa7ab()	Unknown	Non-user code. Binary was not built with debug information.
 	GraphStudioNext.exe!002f5a5e()	Unknown	Non-user code. Binary was not built with debug information.
 	GraphStudioNext.exe!002f6219()	Unknown	Non-user code. Binary was not built with debug information.
 	user32.dll!__InternalCallWinProc@20()	Unknown	Non-user code. Symbols loaded.
 	user32.dll!UserCallWinProcCheckWow()	Unknown	Non-user code. Symbols loaded.
 	user32.dll!DispatchMessageWorker()	Unknown	Non-user code. Symbols loaded.
 	user32.dll!_DispatchMessageW@4()	Unknown	Non-user code. Symbols loaded.
 	GraphStudioNext.exe!003098cf()	Unknown	Non-user code. Binary was not built with debug information.
 	GraphStudioNext.exe!0046913f()	Unknown	Non-user code. Binary was not built with debug information.
 	GraphStudioNext.exe!004431a0()	Unknown	Non-user code. Binary was not built with debug information.
 	kernel32.dll!@BaseThreadInitThunk@12()	Unknown	Non-user code. Symbols loaded.
 	ntdll.dll!__RtlUserThreadStart()	Unknown	Non-user code. Symbols loaded.
 	ntdll.dll!__RtlUserThreadStart@8()	Unknown	Non-user code. Symbols loaded.

**Comment by roman380** [comment]
> pvmjpg21.dll & pvwv220.dll

Here are your likely violators. Just rename then or otherwise move out of system and retry. Some third party app is likely to have them installed. 

You can also resvr32 /u them otherwise to remove from DirectShow registration space.

**Comment by Petje1972** [comment]
Thanks for your help,
Registering and deleting these two items solved the issue
