### ISSUE TITLE
Google file hosting says there's a virus in your release files

### ISSUE THREAD

**Issue by illtellyoulater** [cplussharp/graph-studio-next#338]
Google reports that your release files are infected by a virus and won't let me download the file.
Can you look into that?

Thanks!

**Comment by roman380** [comment]
Let's hope Google updates it database and removes this supposed false positive. Also it's fairly easy to build the apps from source code too.

**Comment by jjgh** [comment]
I was just informing you so could submit it to antivirus engines as a false positive thus allowing the file to be downloaded again... as not everyone has a ready to use building environment.
In my case as a workaround I used the latest version of the 32 bit version.

**Comment by Pysis868** [comment]
Just compiled Release x64 file and it looks fine: https://www.virustotal.com/gui/file/96364397686c2df98f1e3074af6a9ee7d79b4dd8ce851e7d8eefe7e290574543

**Comment by rdp** [comment]
I was able to download OK from https://github.com/cplussharp/graph-studio-next/releases/tag/v0.7.3.1 ?

**Comment by cplussharp** [comment]
I removed the links to the old releases with this commit 8e190038a1768831656587e0c6f284e871e0dcce. Please use the github release page instead: https://github.com/cplussharp/graph-studio-next/releases
