### ISSUE TITLE
Artifact not found or access denied

### ISSUE THREAD

**Issue by ronymarcolino** [cplussharp/graph-studio-next#341]
When i try to download the latest builds (exe and pdb) i receive this message:
 
{"message":"Artifact not found or access denied."}

**Comment by nathanbabcock** [comment]
I'm getting the same error

**Comment by cplussharp** [comment]
I restarted the builds. The results should now be available again. Looks like they are deleted after 6 month. We need more activity/commits here so this does not happen again. ;-)

**Comment by nathanbabcock** [comment]
Thank you @cplussharp :D

**Comment by Pysis868** [comment]
Same problem from the README links today..

**Comment by cplussharp** [comment]
Links are working again, seems like the build artifacts now get deleted after 3 month :-(
