### ISSUE TITLE
Ctrl+C: Copy Screenshot to Clipboard

### ISSUE THREAD

**Issue by sriediger** [cplussharp/graph-studio-next#342]
Currently Ctrl+C copies a screenshot of the graph to the clipboard. 
This prevents that a user can use Ctrl+C to copy text from an edit control of a property page to the clipboard.
My biggest wish would be to assign a different key combination to "Copy Screenshot to Clipboard" and avoid standard Windows shortcuts.

Thank you very much in advance.

P.S: GraphStudioNext is great :-)

**Comment by roman380** [comment]
Do you have any suggestions, that make sense and don't collide with anything else?

**Comment by sriediger** [comment]
A difficult question. 

- Perhaps **Ctrl+Shift+Print Screen**, if this is possible. 
- This combination is not so often used in programs, compared to **Ctrl+C** 
- **Print Screen** is mentally associated with some kind of screenshot
- I know that **Ctrl+Shift+Print Screen** would trigger a screenshot of the whole desktop, but only **Print Screen** alone does the same.

A customization would be a too big effort for the problem, right?

**Comment by roman380** [comment]
I mean I tihnk your concern is totally valid and it's a good idea to change, the question is whether you have a good candidate in mind or somoene is yet to figure that out. PrintScreen itself is handled by OS for desktop capture and also Alt+PrintScreen IIRC. Maybe it should rather be a traditional letter based hotkey, just another one without known conflicts.

**Comment by clsid2** [comment]
Ctrl+F12 is currently used to save to image file. Maybe use Ctrl+Shift+F12 for clipboard? And add it to the menu as well.

**Comment by roman380** [comment]
I will leave #343 for guys to hav a look or otherwise merge in a while (a minor change and makes sense).

> And add it to the menu as well.

They are currently both in menu, one under File, and the other under View. Maybe a bit messy but not that bad.

**Comment by cplussharp** [comment]
I don't think we should just change the short-cut. That could confuse existing users! The more important question is, why is the clipboard command executed on the graph? Does it just bubble up from the the property page or is it never executed on the property page in the first place?

**Comment by roman380** [comment]
These might be two related issues, better shortcut & also disablement of scope where accelerators apply. The original request overall looks valid. Repo steps:

- add a filter like AC3Filter, for example, into graph and open its properties, switch to page with edit control there
- Ctrl+C takes us to `CGraphView::OnViewCopyScreenshotToClipboard`

**Comment by cplussharp** [comment]
@roman380 thanks for your change, I just picked the last commit ( 4dacf1c ) to fix the problem. So the Ctrl+C is not handled in the main window anymore, when a property page (or any other child window/dialog) is active.
